export const PostMokeData = [
  {
    id: 1,
    title: "Unveiling the Power Within: Exploring the Depths of Self-Discovery",
    categories: 'science',
    img: "/assets/images/p11.jpg",
    body: "Embark on a transformative journey of self-discovery as we delve into the uncharted territories of the human psyche, unlocking hidden potentials and gaining profound insights into who we truly are.",
  },
  {
    id: 2,
    title: "Embracing the Unknown: Navigating Life's Mysterious Pathways",
    categories: 'science',
    img: "/assets/images/p12.jpg",
    body: "Embrace uncertainty with courage and wisdom as we traverse life's enigmatic roads, unraveling the mysteries that lie ahead, and finding strength in embracing the unpredictable nature of our existence.",
  },
  {
    id: 3,
    title: "Revolutionizing Style: Embracing Fashion's Ever-Evolving Trends",
    categories: 'art',
    img: "/assets/images/p14.jpg",
    body: "Discover the dynamic world of fashion as we explore the latest trends and innovative style transformations that redefine the way we dress. Unleash your inner fashionista and embrace the constantly evolving landscape of self-expression through clothing.",
  },
  {
    id: 4,
    title: "Sartorial Expression: Unveiling the Artistry of Fashion's Creative Canvas",
    categories: 'crypto',
    img: "/assets/images/p13.jpg",
    body: "Immerse yourself in the captivating realm of fashion's artistic expression, where fabrics become canvases and designs become masterpieces. Unveil the secrets behind sartorial creativity, as we celebrate the profound impact of fashion as an art form and a means of personal storytelling.",
  },
  {
    id: 5,
    title: "Mysteries of the Deep: Exploring the Enigmatic World of Sea Creatures",
    categories: 'Life style',
    img: "/assets/images/p15.jpg",
    body: "Dive into the mesmerizing depths of the ocean and embark on an awe-inspiring adventure as we unravel the secrets of sea creatures. From majestic whales to intricate coral ecosystems, join us in discovering the wonders that inhabit the mysterious and diverse marine world.",
  },
  {
    id: 6,
    title: "Eco-Friendly Dwellings: Nurturing Nature in Green Apartments",
    categories: 'Tec',
    img: "/assets/images/p16.jpg",
    body: "Experience the essence of eco-friendly living within the walls of green apartments. Delve into the world of sustainable architecture, energy-efficient technologies, and nature-inspired designs that promote a healthy coexistence with the environment. Uncover the joys of nurturing nature while enjoying the comforts of an eco-conscious dwelling.",
  },
  {
    id: 7,
    title: "Playful Penguins: Exploring the Charming World of these Adorable Creatures",
    categories: 'Fashion',
    img: "/assets/images/p17.jpg",
    body: "Delight in the enchanting realm of playful penguins as we uncover their endearing antics and unique characteristics. From waddling walks to joyful slides, join us in discovering the charm and charisma of these beloved creatures that captivate hearts worldwide.",
  },
  {
    id: 8,
    title: "Frozen Giants Unveiled: Journeying into the World of Ice-Capped Mountains",
    categories: 'Fashion',
    img: "/assets/images/p18.jpg",
    body: "Venture into the realm of frozen giants, where we unveil the grandeur and majesty of ice-capped mountains. From snow-cloaked summits to ancient glaciers, immerse yourself in the raw power and timeless charm of these awe-inspiring natural wonders. Let us take you on an unforgettable journey through the enchanting world of ice mountains.",
  },
  {
    id: 9,
    title: "Galactic Odyssey: Exploring the Wonders of Our Vast Universe",
    categories: 'art',
    img: "/assets/images/p19.jpg",
    body: "Embark on a mesmerizing galactic odyssey as we journey through the celestial wonders of the universe. From distant stars to swirling galaxies, join us in unraveling the mysteries of space and discovering the breathtaking beauty that lies beyond our Earthly realm.",
  },
  {
    id: 10,
    title: "Enhancing Interiors: The Art of Balancing Tables and Chairs",
    categories: 'Fashion',
    img: "/assets/images/p20.jpg",
    body: "Experience a world of refined interior design as we delve into the enchanting allure of tables and chairs. Discover the perfect blend of functionality and aesthetics, as these essential furniture pieces elevate living spaces with their timeless elegance and thoughtful craftsmanship.",
  },
  {
    id: 11,
    title: "in quibusdam tempore odit est dolorem",
    categories: 'Tec',
    img: "/assets/images/p21.jpg",
    body: "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
  },
  {
    id: 12,
    title: "dolorum ut in voluptas mollitia et saepe quo animi",
    categories: 'art',
    img: "/assets/images/p22.jpg",
    body: "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
  },
  {
    id: 13,
    title: "voluptatem eligendi optio",
    categories: 'AI',
    img: "/assets/images/image13.jpeg",
    body: "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
  },
  {
    id: 14,
    title: "eveniet quod temporibus",
    categories: 'AI',
    img: "/assets/images/image1.jpg",
    body: "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
  },
  {
    id: 14,
    title: "fugit voluptas sed molestias voluptatem provident",
    categories: 'crypto',
    img: "/assets/images/image15.jpg",
    body: "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
  },
];
